# Generated by Django 5.0 on 2023-12-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=50)),
                ('surName', models.CharField(default='', max_length=50)),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('request', models.BooleanField(default=False)),
                ('submitTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
