# Generated by Django 5.0 on 2023-12-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annual',
            name='request',
        ),
    ]
